### ISSUE TITLE
업로드된 이미지 삭제 기능 구현

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/image-hub-platform#13]
## 🖊️ *Description*
아래 유저와 어드민의 이미지 삭제 기능 구현

## ✅ *Todo*
- [ ] 유저는 업로드한 이미지를 개별 / 전체 삭제할 수 있음
- [ ] 어드민은 특정 유저의 모든 이미지를 삭제할 수 있음
- [ ] 어드민은 특정 유저의 특정 이미지를 삭제할 수 있음

## 📗 *Etc*
