### ISSUE TITLE
이미지 삭제 API 호출시 서버의 이미지, 썸네일 병렬(고루틴) 삭제와 순차적 삭제와 성능 비교하기

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/image-hub-platform#14]
## 🖊️ *Description*
고루틴으로 서버 삭제와 순차 삭제의 성능을 비교하고 문서를 작성한다.
## ✅ *Todo*
- [x] 고루틴으로 삭제했을 때 시간 측정
- [x] 순차적으로 삭제했을 때 시간 측정
- [ ] 비교 테스트 문서 작성

## 📗 *Etc*
연관된 이슈: #13

**Comment by zeze1004** [comment]
![image](https://github.com/user-attachments/assets/64de6ac5-b563-469d-82b2-2a5a6995f19c)
테스트 결과 병렬 삭제가 순차적으로 파일을 삭제하는 것보다 더 빠르다
