### ISSUE TITLE
이미지의 카테고리 추가, 삭제에 대한 기능 구현

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/image-hub-platform#18]
## 🖊️ *Description*
특정 이미지에 대해 카테고리 추가 및 삭제에 대한 기능을 구현한다

## ✅ *Todo*
- [ ] 이미지에 대해 추가/삭제하고 싶은 카테고리가 이미 있는지 검증 로직
- [ ] 이미지에 대해 카테고리 추가
- [ ] 이미지에 대해 카테고리 삭제 

## 📗 *Etc*
