### ISSUE TITLE
테스트 코드 작성

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/image-hub-platform#23]
## 🖊️ *Description*
하단의 테스트 구현

## ✅ *Todo*
- [ ] 서비스 단: 이미지 업로드, 조회, 삭제 유닛테스트 구현
- [ ] 서비스 단: 카테고리 조회, 추가, 삭제 유닛테스트 구현
- [ ] 핸들러 단: 테스트 이미지 폴더 만들고, 이미지 조회 엔드포인트 테스트

## 📗 *Etc*
