### ISSUE TITLE
JWT 토큰으로 일반 유저와 관리자 권한 구분하는 로직 구현

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/image-hub-platform#3]
## 🖊️ *Description*
미들웨어에서 JWT에서 추출한 ID를 데이터베이스에 조회해서 인증된 계정인지 권한이 무엇인지 등을 확인함

## ✅ *Todo*
- [x] User 데이터 구조 생성
- [ ] 미들워에단 구현
- [x] JWT 에서 Claims 객체 추출 로직 구현
- [ ] 계정 검증용 엔드포인트 구현

## 📗 *Etc*
