### ISSUE TITLE
유저와 관리자의 이미지 업로드 기능 구현

### ISSUE THREAD

**Issue by zeze1004** [zeze1004/image-hub-platform#5]
## 🖊️ *Description*
이미지 업로드 기능 구현

## ✅ *Todo*
- [ ] 이미지 업로드 API 구현
- [ ] 서버에 유저별 이미지 디렉토리 생성 후 이미지 저장
- [ ] params에 userID가 추가되면 관리자 롤인지 검증 후에 해당 유저 이미지 디렉토리에 이미지 업로드
- [ ] DB에 이미지 메타데이터 저장
  - [ ] 파일명, 업로드 날짜, 설명 등

## 📗 *Etc*
